{% set name = "reacnetgenerator" %}
{% set version = "1.6.15" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deepmodeling/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 69e3fb5155320e243488cb30e289d85b0c6c0d5991577af6acd2955cec0756f8

build:
  number: 1
  skip: true  # [is_abi3 and not is_python_min]
  python_version_independent: true   # [is_abi3]
  entry_points:
    - reacnetgenerator = reacnetgenerator.commandline:_commandline
    - reacnetgeneratorgui = reacnetgenerator.gui:gui
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [unix]
    - set SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake >=3.26
    - make  # [unix]
    - nodejs
  host:
    - python-abi3  # [is_abi3]
    - python
    - pip
    - cython >=0.24.1
    - setuptools_scm
    - scikit-build-core >=0.9.0
    - pyyaml
  run:
    - python
    - openbabel
    - rdkit >=2018.09
    - numpy
    - pandas
    - networkx
    - matplotlib-base
    - hmmlearn >=0.2.1
    - ase
    - scour
    - tqdm >=4.9.0
    - coloredlogs
    - lz4
    - requests
    - packaging

test:
  imports:
    - reacnetgenerator
  requires:
    - pip
    - abi3audit  # [is_abi3]
  commands:
    - pip check
    - abi3audit $SP_DIR/dps.abi3.so -s -v --assume-minimum-abi3 {{ python_min }}  # [unix and is_abi3]
    - abi3audit %SP_DIR%/dps.pyd -s -v --assume-minimum-abi3 {{ python_min }}  # [win and is_abi3]
    - reacnetgenerator -h

about:
  home: http://github.com/deepmodeling/reacnetgenerator
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: An automatic generator of reaction network for reactive molecular dynamics simulation.
  doc_url: https://docs.deepmodeling.com/projects/reacnetgenerator/
  dev_url: https://github.com/deepmodeling/reacnetgenerator

extra:
  recipe-maintainers:
    - njzjz
    - Eipgen
